### PR TITLE
add scoped_session support

### PR DESCRIPTION
**Pull request by dingyaguang117**
I'm trying to solve the problem below

```
db = SQLAlchemy()

class User(db.Model):
    __tablename__ = 'users'

    id = Column(BigInteger, primary_key=True)
    username = Column(String(64), unique=True)

    def __init__(self, username):
        self.username = username

    # for every method, the session argument is necessary but tedious,
    # if there are more nest calls, we had to pass the session argument again and again 
    @classmethod
    def count(cls, session):  
        return session.query(cls).count()

```

so, I add scoped_session (learned from flask_sqlalchemy), which will shorten the statement.

This is the improved way to write it

```
class User(db.Model):
    __tablename__ = 'users'

    id = Column(BigInteger, primary_key=True)
    username = Column(String(64), unique=True)

    def __init__(self, username):
        self.username = username

    @classmethod
    def count(cls):
        return db.session.query(cls).count()

```

The problem is this enhancement only support python3.7+, because `contextvars` is used.

### CODE REVIEW

**Comment by siddhantgoel** [comment]
Hey, could you pull in the latest master and rebase your changes on top?

**Comment by dingyaguang117** [comment]
> Hey, could you pull in the latest master and rebase your changes on top?

I had merged the latest master. This PR contains 5 commits, three behind the master and two ahead. So it looks like a lot of commits, but only 3 files changed.

**Comment by siddhantgoel** [comment]
I squashed all your commits from the previous PR into one commit, which is probably why this is happening. Because in this PR I see 22 commits.

**Comment by siddhantgoel** [comment]
I'm somehow not completely convinced about this change. Firstly, we already have a `session` associated with every request. After this change is merged, there would be potentially two. Secondly, if now there are 2 sessions with every request, there's a possibility that if there are changes being made on one session, they're not updated on the second one, resulting in inconsistent data across those two sessions.

**Comment by dingyaguang117** [comment]
> I'm somehow not completely convinced about this change. Firstly, we already have a `session` associated with every request. After this change is merged, there would be potentially two. Secondly, if now there are 2 sessions with every request, there's a possibility that if there are changes being made on one session, they're not updated on the second one, resulting in inconsistent data across those two sessions.

yes, we'd better make  self.session and db.session refer to the same one. or just keep one

**Comment by siddhantgoel** [comment]
That would require a bit more work, I think. I'd like to release the multiple sessions support first, and after that we can come back to this PR.

**Comment by dingyaguang117** [comment]
sure!

**Comment by dingyaguang117** [comment]
There is a big problem. This implement didn't support as_future.

Because the sql executing is in AsyncExecution's ThreadPool which can not fetch the contextvar.

**Comment by siddhantgoel** [comment]
Yeah, problems like these are why I'm skeptical of this change. :man_shrugging:

**Comment by siddhantgoel** [comment]
Also, `ContextVar` is 3.7 only, so that's another issue I see.

**Comment by siddhantgoel** [comment]
@dingyaguang117 I'm wondering how we can proceed with this PR. what's your opinion?

**Comment by dingyaguang117** [comment]
> There is a big problem. This implement didn't support as_future.
> 
> Because the sql executing is in AsyncExecution's ThreadPool which can not fetch the contextvar.

@siddhantgoel  Hi， buddy！

I think I have sovled this problem. These are my improvement.


```
import contextvars
import threading

request_id = contextvars.ContextVar('request_id')


def get_context_id():
    # this works well with as_future
    try:
        return 'request-' + request_id.get()
    except LookupError:
        return 'thread-' + str(threading.get_ident())


def set_request_id(_id):

    request_id.set(_id)

```



```
class SessionMixin:

    def prepare(self):
        request_id = '%03d-%d' % (id(self.request) % 1000, time.time() * 100000, )
        set_request_id(request_id)

    def on_finish(self):
            ....
            db.session.remove()


```

It works well on my project. I will complete this PR later.

**Comment by siddhantgoel** [comment]
Hey, I've changed the default branch to main which is why Github closed this PR. But please feel free to set the base to the new branch!

**Pull request closed without merging**
